import { z } from "zod";

export const ZDeviceParam = z.object({ devId: z.string() });
export const ZDevice = z.object({
  devId: z.string().optional(),
  wardId: z.string().optional(),
  devSerial: z.string().optional(),
  devName: z.string().optional(),
  devDetail: z.string().optional(),
  devStatus: z.boolean().optional(),
  devSeq: z.number().optional(),
  devZone: z.string().optional(),
  installLocation: z.string().optional(),
  locationPic: z.string().optional(),
  installDate: z.date().optional(),
  devIp: z.string().optional(),
  devMacAddEth: z.string().optional(),
  devMacAddWiFi: z.string().optional(),
  devSubNet: z.string().optional(),
  devGetway: z.string().optional(),
  devDns: z.string().optional(),
  firmwareVersion: z.string().optional(),
  invoice: z.string().optional(),
  createBy: z.string().optional(),
  comment: z.string().optional(),
  backupStatus: z.string().optional(),
  moveStatus: z.string().optional(),
  alarn: z.string().optional(),
  duration: z.number().optional(),
  sim: z.string().optional(),
  backToNormal: z.boolean().optional(),
  repeat: z.number().optional(),
  notification: z.boolean().optional(),
  sendEmail: z.string().optional(),
  topic: z.string().optional()
});